title: SubTrack Legal
description: Privacy Policy and Terms of Service for the SubTrack app
theme: jekyll-theme-minimal
markdown: kramdown
permalink: /:basename
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - privacy.md
  - terms.md
